# Generated by Django 3.0.6 on 2020-05-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('middleName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('aadhar', models.IntegerField()),
                ('createdDate', models.DateField(auto_now=True)),
                ('createdDateTime', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('birthDate', models.DateField()),
                ('referral_type', models.CharField(choices=[('Doctor', 'Doctor'), ('Patient', 'Patient'), ('Friend', 'Friend'), ('Other', 'Other')], max_length=7)),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(max_length=200)),
                ('address_line3', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('note1', models.TextField(blank=True)),
                ('note2', models.TextField(blank=True)),
            ],
        ),
    ]
