# Generated by Django 3.0.6 on 2020-05-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address_line1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='address_line2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='address_line3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='referral_type',
            field=models.CharField(blank=True, choices=[('Doctor', 'Doctor'), ('Patient', 'Patient'), ('Friend', 'Friend'), ('Other', 'Other')], max_length=7),
        ),
    ]
