# Generated by Django 3.0.6 on 2020-05-29 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgmt', '0002_auto_20200529_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('First Consultation', 'First Consultation'), ('Routine Checkup', 'Routine Checkup'), ('Medicine Only', 'Medicine Only')], default='Routine Checkup', max_length=20)),
                ('amt_due', models.IntegerField()),
                ('caseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_mgmt.Person')),
            ],
        ),
    ]
