# Generated by Django 3.0.6 on 2020-05-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgmt', '0003_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visitDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='visitDateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
