# Generated by Django 3.0.6 on 2020-05-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgmt', '0004_auto_20200529_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default='Cash', max_length=6),
        ),
    ]
