# Generated by Django 3.0.6 on 2020-06-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgmt', '0006_visit_amt_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Transfer', 'Transfer'), ('Credit', 'Credit')], default='Cash', max_length=8),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_type',
            field=models.CharField(choices=[('First Consultation', 'First Consultation'), ('Routine Checkup', 'Routine Checkup'), ('Medicine Only', 'Medicine Only'), ('For Payment', 'For Payment')], default='Routine Checkup', max_length=20),
        ),
    ]
